In [20]:
text_file = open("input.txt", "r")
lines = text_file.readlines()
x = [int(x.strip()) for x in lines]
text_file.close()

print(x)

[1695, 1157, 1484, 1717, 622, 1513, 1924, 63, 1461, 1971, 1382, 1587, 1913, 1665, 1464, 1914, 1637, 1527, 1424, 1361, 1187, 272, 1909, 1448, 1623, 1164, 1931, 1646, 1096, 1655, 1962, 1961, 1694, 1792, 1989, 1616, 138, 1887, 1357, 1965, 1085, 308, 2007, 1254, 1179, 1124, 1719, 1467, 1928, 1630, 1676, 1359, 1241, 1511, 1413, 1656, 1818, 1919, 1422, 1745, 1208, 1609, 1544, 1775, 1154, 1057, 1440, 1242, 1202, 1266, 1305, 1836, 1760, 1730, 1396, 1315, 1496, 1964, 1300, 1195, 1583, 1607, 1743, 1682, 1453, 1848, 1320, 1601, 954, 1473, 1847, 1486, 1853, 1668, 1342, 1087, 1139, 1349, 1568, 1728, 1420, 1233, 1073, 1376, 1658, 1477, 1871, 1958, 1950, 1503, 1758, 1474, 1203, 1336, 1981, 1309, 1618, 1846, 1974, 1940, 1333, 1119, 1756, 1918, 961, 1307, 1375, 1346, 1611, 1284, 84, 1754, 1608, 2010, 1341, 1136, 1218, 1882, 1911, 1288, 1930, 1749, 1952, 1556, 1757, 1761, 1112, 1963, 1186, 1373, 1622, 1973, 1330, 1508, 1222, 1226, 1389, 1679, 1584, 1237, 1563, 1763, 1998, 1293, 1642, 95, 1661, 1674, 1100, 1262, 1895, 1548, 1400, 1205, 1435, 1156, 1034, 1577, 1701, 1198, 1173, 1500, 1858, 1809, 1780, 1412, 1982, 1070, 1523, 1776, 1598, 1113, 1144, 1777, 1313, 1102, 1999, 1405, 1784, 1196]

In [23]:
x.sort()
x

[63,
 84,
 95,
 138,
 272,
 308,
 622,
 954,
 961,
 1034,
 1057,
 1070,
 1073,
 1085,
 1087,
 1096,
 1100,
 1102,
 1112,
 1113,
 1119,
 1124,
 1136,
 1139,
 1144,
 1154,
 1156,
 1157,
 1164,
 1173,
 1179,
 1186,
 1187,
 1195,
 1196,
 1198,
 1202,
 1203,
 1205,
 1208,
 1218,
 1222,
 1226,
 1233,
 1237,
 1241,
 1242,
 1254,
 1262,
 1266,
 1284,
 1288,
 1293,
 1300,
 1305,
 1307,
 1309,
 1313,
 1315,
 1320,
 1330,
 1333,
 1336,
 1341,
 1342,
 1346,
 1349,
 1357,
 1359,
 1361,
 1373,
 1375,
 1376,
 1382,
 1389,
 1396,
 1400,
 1405,
 1412,
 1413,
 1420,
 1422,
 1424,
 1435,
 1440,
 1448,
 1453,
 1461,
 1464,
 1467,
 1473,
 1474,
 1477,
 1484,
 1486,
 1496,
 1500,
 1503,
 1508,
 1511,
 1513,
 1523,
 1527,
 1544,
 1548,
 1556,
 1563,
 1568,
 1577,
 1583,
 1584,
 1587,
 1598,
 1601,
 1607,
 1608,
 1609,
 1611,
 1616,
 1618,
 1622,
 1623,
 1630,
 1637,
 1642,
 1646,
 1655,
 1656,
 1658,
 1661,
 1665,
 1668,
 1674,
 1676,
 1679,
 1682,
 1694,
 1695,
 1701,
 1717,
 1719,
 1728,
 1730,
 1743,
 1745,
 1749,
 1754,
 1756,
 1757,
 1758,
 1760,
 1761,
 1763,
 1775,
 1776,
 1777,
 1780,
 1784,
 1792,
 1809,
 1818,
 1836,
 1846,
 1847,
 1848,
 1853,
 1858,
 1871,
 1882,
 1887,
 1895,
 1909,
 1911,
 1913,
 1914,
 1918,
 1919,
 1924,
 1928,
 1930,
 1931,
 1940,
 1950,
 1952,
 1958,
 1961,
 1962,
 1963,
 1964,
 1965,
 1971,
 1973,
 1974,
 1981,
 1982,
 1989,
 1998,
 1999,
 2007,
 2010]

In [25]:
list1 = [1, 2, 3, 4, 5, 6]
list2 = [100, 300, 500]

for x in list1:
    # while x=1
    for y in list2:
        if x + y == 504:
            print("FOUND ONE")
            print(x)
            print(y)

1
2
3
4
5
6